// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The Avishek Authors. All rights reserved.

final class Asset {
  static const AssetSocial social = AssetSocial();
  static const AssetIcons icons = AssetIcons();
  static const AssetNav nav = AssetNav();
}

final class AssetSocial {
  const AssetSocial();

  String get fb => 'assets/social-bin/fb.svg.vec';
  String get google => 'assets/social-bin/google.svg.vec';
}
final class AssetIcons {
  const AssetIcons();

  String get fb => 'assets/icons-bin/fb.svg.vec';
  String get x => 'assets/icons-bin/x.svg.vec';
  String get day => 'assets/icons-bin/day.svg.vec';
  String get k => 'assets/icons-bin/k.svg.vec';
  String get chat => 'assets/icons-bin/chat.svg.vec';
  String get night => 'assets/icons-bin/night.svg.vec';
  String get google => 'assets/icons-bin/google.svg.vec';
}
final class AssetNav {
  const AssetNav();

  String get search => 'assets/nav-bin/search.svg.vec';
  String get home => 'assets/nav-bin/home.svg.vec';
  String get add => 'assets/nav-bin/add.svg.vec';
  String get profile => 'assets/nav-bin/profile.svg.vec';
}
