name: shoesly
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod:
  freezed:
  json_serializable:
  flutter_animate:
  json_annotation:
  go_router: ^11.1.3
  shape_of_view_null_safe:
  flutter_inappwebview: ^6.0.0
  flutter_dotenv: ^5.1.0

  dio:
  freezed_annotation:
  cached_network_image: ^3.3.1

  hive:
  firebase_core: ^2.4.0
  google_sign_in: ^5.4.2
  firebase_auth: ^4.2.3
  dartz:

  shoesly_components: any
  shoesly_resources: any
  hive_flutter: ^1.1.0
  retrofit: ^4.1.0
  carousel_slider: ^4.2.1
  flutter_switch: ^0.3.2
  fancy_switch: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner:

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  injectable: ^2.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
